### ISSUE TITLE
Can't start app in Mix release {:bad_return, {{:telemetry_app, :start...

### ISSUE THREAD

**Issue by flurin** [beam-telemetry/telemetry#102]
Using Telemetry from git (sha: `9a9da7b8`) the telemetry app won't work in a mix release. It works fine when starting the application with mix.

This is the error we get when trying to start the release:

```
[14:02:39.213] [error] module=proc_lib function=crash_report/4 
Process #PID<0.3570.0> terminating
** (exit) {:bad_return, {{:telemetry_app, :start, [:normal, []]}, {:EXIT, {:undef, [{:telemetry_app, :start, [:normal, []], []}, {:application_master, :start_it_old, 4, [file: 'application_master.erl', line: 293]}]}}}}
    (kernel 8.1.2) application_master.erl:142: :application_master.init/4
    (stdlib 3.16.1) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Initial Call: :application_master.init/4
Ancestors: [#PID<0.3569.0>]
Message Queue Length: 1
Messages: [{:EXIT, #PID<0.3571.0>, :normal}]
Links: [#PID<0.3569.0>, #PID<0.3496.0>]
Dictionary: []
Trapping Exits: true
Status: :running
Heap Size: 376
Stack Size: 28
Reductions: 225
```

**Comment by flurin** [comment]
@josevalim That does fix the problem! Thank you very much.

Any idea when the next release is planned?

**Comment by josevalim** [comment]
The mix.exs itself was not released yet, which means this fixed only a bug in master, so there is no pressure for a new release. :)

**Comment by bryannaegele** [comment]
Yeah, we just haven't had a release since before the failure event was merged in October, so that's still sitting here.

https://github.com/beam-telemetry/telemetry/pull/98

**Comment by josevalim** [comment]
Ah, so if we want a new release regardless, I can do it. :)

**Comment by josevalim** [comment]
Still using Rebar!

**Comment by bryannaegele** [comment]
Yes, I think we should still do a release regardless to get that out. It doesn't solve anything @hubertlepicki raised in #106 but it will give him functionality to monitor failed handlers and make some decision based upon that.

**Comment by josevalim** [comment]
@arkgil can you please ship it? I thought I would carve time but my arm injury is not helping. :) thank you!
