### ISSUE TITLE
Is telemetry distributed ?

### ISSUE THREAD

**Issue by tiagodavi** [beam-telemetry/telemetry#114]
I am wondering if I have two nodes connected via libcluster and I run telemetry.attach on node A and telemetry.execute on B. If node A is able to execute the handle_event automatically. 

Or how can I achieve this with telemetry? 

Thank you.

**Comment by josevalim** [comment]
No, it is per node. You would need to attach handlers that sends the events across nodes.

**Comment by tiagodavi** [comment]
Thank you @josevalim
