### ISSUE TITLE
Automatically detach when attaching process ends

### ISSUE THREAD

**Issue by cjbottaro** [beam-telemetry/telemetry#115]
I have a use case where a GenServer needs to monitor a connection. The connection automatically reconnects when it disconnects, and it publishes telemetry events for it.

The problem is my GenServer can crash and get restarted, but :telemetry doesn't clean up the event handler.

```elixir
Task.async(fn -> :ok = :telemetry.attach(:foo, :foo, &handler/4, :foo) end)
|> Task.await()

:telemetry.list_handlers(:foo) != []
```

Is there any performant way to have :telemetry `Process.monitor/1` anything that calls `attach/4` and automatically detaches when those processes end?

There are ways to do this on the user side of :telemetry, but it seems very hacky: The config argument of attach could be `{handler_id, pid_of_caller`}, then the handler can call `Process.alive?(pid_of_caller)` and call `detach` if true. It also seems less performant than just having a process monitor.

Thanks for the help.

**Comment by josevalim** [comment]
Monitor is the way to go. Monitor it and remove it in the DOWN message. :)

for a GenServer, you may also be fine with trapping exits and a terminate callback.
