### ISSUE TITLE
Using telemetry as a dependency in an Elixir script

### ISSUE THREAD

**Issue by yrashk** [beam-telemetry/telemetry#119]
I've got a previously working Elixir script with `Mix.install`:

```elixir
Mix.install([
  {:telemetry, "~> 1.1.0"},
])
```

I've recently upgraded to macOS Ventura (on M1) and tried to run the script (`elixir test.exs`), and I get this error:

```
** (ErlangError) Erlang error: :enoent
(elixir 1.14.2) lib/system.ex:940: System.shell("/Users/yrashk/.mix/elixir/1-14/rebar3 bare compile --paths /Users/yrashk/Library/Caches/mix/installs/elixir-1.14.2-erts-13.1.1/c0c70753ffb5bc2d1e26727be812c93b/_build/dev/lib/*/ebin", [stderr_to_stdout: true, into: %Mix.Shell{callback: #Function<0.74950258/1 in Mix.Shell.IO.cmd/2>}, env: [{"ERL_LIBS", "/Users/yrashk/Library/Caches/mix/installs/elixir-1.14.2-erts-13.1.1/c0c70753ffb5bc2d1e26727be812c93b/_build/dev/lib"}, {"REBAR_BARE_COMPILER_OUTPUT_DIR", "/Users/yrashk/Library/Caches/mix/installs/elixir-1.14.2-erts-13.1.1/c0c70753ffb5bc2d1e26727be812c93b/_build/dev/lib/telemetry"}, {"REBAR_CONFIG", "/Users/yrashk/Library/Caches/mix/installs/elixir-1.14.2-erts-13.1.1/c0c70753ffb5bc2d1e26727be812c93b/_build/dev/lib/telemetry/mix.rebar.config"}, {"REBAR_PROFILE", "prod"}, {"TERM", "dumb"}]])
```

```
$ elixir --version
Erlang/OTP 25 [erts-13.1.1] [source] [64-bit] [smp:10:10] [ds:10:10:10] [async-threads:1] [jit] [dtrace]
```

Not quire sure what went wrong here... I've tried deleting all the caches, didn't help.

**Comment by josevalim** [comment]
What does `System.find_executable("sh")` return?

**Comment by yrashk** [comment]
`nil`

**Comment by josevalim** [comment]
I just had someone else check and they got `/bin/sh` on their Ventura.

**Comment by yrashk** [comment]
It *is* there:

```
$ which sh
/bin/sh
```

**Comment by josevalim** [comment]
Weird. So what is your PATH inside Elixir?

**Comment by josevalim** [comment]
Also what does `:file.read_file_info("/bin/sh")` return?

**Comment by yrashk** [comment]
```
iex(1)> :file.read_file_info("/bin/sh")
{:ok,
 {:file_info, 134000, :regular, :read, {{2022, 10, 28}, {1, 43, 33}},
  {{2022, 10, 28}, {1, 43, 33}}, {{2022, 10, 28}, {1, 43, 33}}, 33261, 1,
  16777231, 0, 542645, 0, 0}}
```

**Comment by josevalim** [comment]
It all looks good to me. I have no idea then. You can see the line raising the error here: https://github.com/elixir-lang/elixir/blob/v1.14/lib/elixir/lib/system.ex#LL940C22-L940C49

**Comment by yrashk** [comment]
I think I may be onto something. I use `fish` shell, and according to their [docs](https://fishshell.com/docs/current/tutorial.html#path) PATH is not a colon-delimited string.

The also say:

For compatibility with other shells and external commands, $PATH is a [path variable](https://fishshell.com/docs/current/language.html#variables-path), and so will be joined with colons (not spaces) when you quote it:

```
echo "$PATH"
/usr/local/sbin:/usr/local/bin:/usr/bin
```

When I look at my $PATH as is, there's a " /bin " entry. When I quote it (`echo "$PATH"`) it disappears from the list. 

Not sure why this has manifested just now.

**Comment by yrashk** [comment]
And yes, sorry for the noise, it seems to be completely unrelated to this library!
