### ISSUE TITLE
OTP 27 docs

### ISSUE THREAD

**Issue by whatyouhide** [beam-telemetry/telemetry#133]
Yo! You folks interested in moving the docs to `-doc` docs from OTP 27? Simplifies the syntax quite a bit thanks to Markdown. I started working on this but figured I'd ask first 🙃

**Comment by wojtekmach** [comment]
@whatyouhide sorry if stating the obvious, I was looking into doing same for hex_core and the following approach with `?MODULEDOC` and `?DOC` macros seems promising:

```erlang
-module(foo).
-export([foo/0]).

-if(?OTP_RELEASE >= 27).
-define(MODULEDOC(Str), -moduledoc(Str)).
-define(DOC(Str), -doc(Str)).
-else.
-define(MODULEDOC(Str), -compile([])).
-define(DOC(Str), -compile([])).
-endif.

?MODULEDOC("""
The foo module.
""").

?DOC("""
The foo module.
""").
foo() ->
  ok.
```

**Comment by whatyouhide** [comment]
@wojtekmach that's not obvious at all! Yeah I thought this was not needed as `-doc` attrs would just be ignored, but the issue is `"""` strings which are not supported <27. Great catch!

**Comment by whatyouhide** [comment]
Closing in favor of #134.
