### ISSUE TITLE
Rebar3 error when trying to compile or do anything with this project

### ISSUE THREAD

**Issue by 0skar16** [beam-telemetry/telemetry#136]
Rebar3 crashes when trying to compile (or even execute rebar3 itself in the directory)

Log

```
===> Uncaught error in rebar_core. Run with DIAGNOSTIC=1 to see stacktrace or consult rebar3.crashdump
===> Uncaught error: function_clause
===> Stack trace to the error location:
[{rebar_plugins,'-discover_plugins/2-fun-0-',
                [rebar3_hex],
                [{file,"/builddir/build/BUILD/rebar3-3.24.0/apps/rebar/src/rebar_plugins.erl"},
                 {line,191}]},
 {lists,filtermap_1,2,[{file,"lists.erl"},{line,1661}]},
 {rebar_plugins,discover_plugins,2,
                [{file,"/builddir/build/BUILD/rebar3-3.24.0/apps/rebar/src/rebar_plugins.erl"},
                 {line,191}]},
 {rebar_plugins,handle_plugins,4,
                [{file,"/builddir/build/BUILD/rebar3-3.24.0/apps/rebar/src/rebar_plugins.erl"},
                 {line,98}]},
 {lists,foldl,3,[{file,"lists.erl"},{line,1594}]},
 {rebar_plugins,project_plugins_install,1,
                [{file,"/builddir/build/BUILD/rebar3-3.24.0/apps/rebar/src/rebar_plugins.erl"},
                 {line,24}]},
 {rebar3,run_aux,2,
         [{file,"/builddir/build/BUILD/rebar3-3.24.0/apps/rebar/src/rebar3.erl"},
          {line,186}]},
 {rebar3,main,1,
         [{file,"/builddir/build/BUILD/rebar3-3.24.0/apps/rebar/src/rebar3.erl"},
          {line,66}]}]
```

**Comment by tsloughter** [comment]
I can't reproduce. Is there anything else you can tell me about your environment that may be unique? What version of Erlang? What exact commands are you running? I see your rebar3 is is in `/builddir/build/BUILD/rebar3-3.24.0/` what environment is this you are running in?

**Comment by 0skar16** [comment]
> I can't reproduce. Is there anything else you can tell me about your environment that may be unique? What version of Erlang? What exact commands are you running? I see your rebar3 is is in `/builddir/build/BUILD/rebar3-3.24.0/` what environment is this you are running in?

Apparently, it may have been a version mismatch (?) I reinstalled everything with asdf instead of the ones available on the fedora fepos and now everything works, sorry for the confusion
