### ISSUE TITLE
Question: Is there a more detailed usage example?

### ISSUE THREAD

**Issue by nelsonic** [beam-telemetry/telemetry#22]
Hi! Saw Chris' describe Telemetry in his Elixir Conf Talk and want to explore _using_ it.

Is there a more detailed usage example available somewhere 
or "demo" app with source we can read on GitHub to help get started using it?

Is it likely to be covered in Programming Elixir 1.6 or Programming Phoenix 1.4 ?
(_I've tried searching the latest versions of both eBooks and not found a reference to Telemetry..._)

Thanks!

P.S. LMK if this is more appropriate for the ElixirForum, happy to close this issue and move it to there ...

**Comment by josevalim** [comment]
The lib is really small, so all there is to it is in the README. You dispatch events with Telemetry.execute and you receive them with Telemetry.attach. But yes, it is best to move this discussion to the forum.

It may be covered in future editions of the Programming Phoenix, but we can't confirm. It is not used by Phoenix v1.4 though.

**Comment by nelsonic** [comment]
Thanks for confirming @josevalim 👍
