### ISSUE TITLE
Distributed Tracing - ie: mutable handlers

### ISSUE THREAD

**Issue by binaryseed** [beam-telemetry/telemetry#24]
Howdy folks, I'm excited about this project!

I'm the author of the New Relic Elixir Agent (https://github.com/newrelic/elixir_agent/)...

One feature that is really powerful but a little aside from the Telemetry use cases I'm seeing is Distributed Tracing. This kind of features differs in that in addition to callbacks that fire when events happen, we need make some kind of mutation.

For HTTP, this looks like adding an additional header to a request.. In the New Relic agent, the header addition pretty much has to be done manually by the developer. 

```elixir
headers = headers ++ NewRelic.create_distributed_trace_payload(:http)
```

On the receiving end, the server needs to get access to read this header and take some action. We do this with a simple plug that users must add to the top of their pipeline. You could imagine reading the header and wanting to set some kind of value in `conn.private`, for example.

If we provided a clear convention or mechanism for this kind of thing, libraries might be willing to build this in along with the Telemetry events. Basically it boils down to enabling the Telemetry system to have a category of event that can transform some select pieces of data.

Here's a very rough sketch of what the interface could be like, just to explain the idea:

```elixir
# Inside an HTTP client
#  ... this library wants to allow transforming headers & query params
%{headers: headers, params: params} =
  Telemetry.transform([:http, :client, :pre_request], %{params: params, headers: headers, url: url, body: body}})

# Inside an HTTP server / Plug
%{conn: conn} = 
  Telemetry.transform([:http, :server, :receive], %{conn: conn})
```

Hopefully this is interesting to other folks too!

**Comment by josevalim** [comment]
Hi @binaryseed!

We know that we don't have all of the tools to support tracing for now but that's pretty much on purpose for now, as we want to solve the most common cases first and collect feedback.

We hope to resume this discussion in some time in the future. :)

Thanks for writing!

**Comment by binaryseed** [comment]
Makes sense! Thanks 

FYI, the architecture of this project is looking really good
