### ISSUE TITLE
How to handle telemetry in tests

### ISSUE THREAD

**Issue by tcoopman** [beam-telemetry/telemetry#27]
I have some code that attaches Telemetry handlers on startup of some supervisor. I start this supervisor in tests with `start_supervised!`, but the problem is that the telemetry handlers are never detached when the supervisor dies.

The code below shows the problem, test `"two"` will fail with the error `{:error, :already_exists}`. I don't really like to  just ignore the outcome of `Telemetry.attach`, I could of course handle both `:ok` and `{:error, :already_exists}` as valid outcomes.

Is that the way to handle it, or is there a way to stop the Telemetry cleanly after a test.

```elixir
defmodule TestTelemetry do
  use ExUnit.Case, async: false

  test "one" do
    :ok = Telemetry.attach_many(
      "log-response-handler",
      [[:external_message, :consumed], [:external_message, :received]],
      LogResponseHandler,
      :handle_event,
      nil
    )
  end

  test "two" do
    :ok = Telemetry.attach_many(
      "log-response-handler",
      [[:external_message, :consumed], [:external_message, :received]],
      LogResponseHandler,
      :handle_event,
      nil
    )
  end
end

```

**Comment by josevalim** [comment]
You can do `{"log-response-handler", System.unique_integer()}` or do `{"log-response-handler", config.test}` assuming you define them as `test "two", config` and so on.
