### ISSUE TITLE
Update docs on hexdocs

### ISSUE THREAD

**Issue by victorolinasc** [beam-telemetry/telemetry#42]
Hi! The hosted docs are still on 0.3 and that is a bit confusing since the change on API.

Could you guys update it there? https://hexdocs.pm/telemetry/

Thanks!

**Comment by arkgil** [comment]
@victorolinasc thanks for spotting! I'll push the updated docs after we merge #43 :)

**Comment by arkgil** [comment]
@victorolinasc I think that the docs were correct, only the version number wasn't bumped properly. Anyway, I pushed new docs, let me know if that solves the issue :)

**Comment by victorolinasc** [comment]
Perfect! I was a bit confused but everything is perfect now! Thanks :)
