### ISSUE TITLE
Telemetry should also use Erlang's Logger data in events

### ISSUE THREAD

**Issue by hauleth** [beam-telemetry/telemetry#49]
This would allow for example using Telemetry events as events in traces (not only as start-end events).

---

My original use-case was a little bit different though. I wanted to add support for [`Server-Timing`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Server-Timing) header in Plug with timings for different parts of the query. This would be grat to gather all events that happened within single request and put them in the response header, however right now there is no way to detect which are the events for "current request" as there is no way to set metadata that would be populated through all Telemetry events. It would be great to have either `telemetry:set_process_metadata/1` or use Erlang's logger metadata that would be added to the metadata provided in event dispatch. With metadata I could just do `set_process_metadata(#{?MODULE => ref})` and use that to detect events that happened within single process.

**Comment by josevalim** [comment]
This has come up in the last Observability WG meeting and the reason why we don't need this is because Telemetry runs in the caller. So in your telemetry callback, you can access pdict, logger, etc.

**Comment by bryannaegele** [comment]
Is there a reason attaching a handler and reading/writing to logger metadata wouldn't work?

**Comment by hauleth** [comment]
@josevalim you know, the Erlang's `logger` handlers work in the caller process as well and the metadata is passed to them anyway.

**Comment by josevalim** [comment]
@hauleth I am aware but the goal of telemetry was always to be very small. Logger is meant to be a complete solution. And, generally speaking, instead of introducing another place for metadata in telemetry, I would rather prefer everyone just converge on logger metadata.

**Comment by hauleth** [comment]
@josevalim that is why I am proposing to do `maps:merge(logger:get_process_metadata(), Metadata)` before passing metadata to the handler. This would:

- converge everyone on logger metadata
- do not require user to depend on fact that handler and dispatcher run in the same process

**Comment by josevalim** [comment]
Right and I am saying the handlers can do it by themselves without imposing anything on telemetry and handlers that do not care about this do not have to worry about it.

**Comment by hauleth** [comment]
@josevalim my point is that doing such in handlers will:

- bring hidden differences between different handlers (for example `telemetry_metrics_statsd` will behave differently form `telemetry_metrics_influxdb` if one of them will decide to support `logger` metadata and other will not or will lag with supporting it)
- above would cause users to not trust the provided handlers and it will be "more secure" to write their own instead of using ones provided by the community

**Comment by hauleth** [comment]
@josevalim my point is that doing such in handlers will:

- bring hidden differences between different handlers (for example `telemetry_metrics_statsd` will behave differently form `telemetry_metrics_influxdb` if one of them will decide to support `logger` metadata and other will not or will lag with supporting it)
- above would cause users to not trust the provided handlers and it will be "more secure" to write their own instead of using ones provided by the community

**Comment by josevalim** [comment]
I am aware of all of those concerns, none of them still wins over the fact telemetry is meant to be a small library and I don't want to impose external concerns if it is not necessary. This is the third place we are having this discussion, I don't think my opinion is going to change, sorry. So we will have to agree to disagree.
