### ISSUE TITLE
A doubt about sync nature of execute

### ISSUE THREAD

**Issue by Kitton** [beam-telemetry/telemetry#51]
Hello, before all thanks for creating a really cool & needed library. 
I have a doubt, as I understand from the code after calling `:telemetry.execute` we call linked handler function immediately in a sync way. Am I right? 
If I am, I have doubts if in some cases (with a high-frequency usage, `ecto`, for example) it will be an optimal solution. Can you please clarify on this topic?

**Comment by josevalim** [comment]
Yes, it is sync. We have done many benchmarks originally and the dispatch of calling the handler itself is negligible. However, the handler should also be responsible to do as little work as possible.

**Comment by Kitton** [comment]
@josevalim thanks for the quick response.  Is it possible to highlight it clearly in Readme?
 Because in some cases (e.g. sending metrics to external service attached to ecto) it can make sense to wrap logic inside hander in async.

**Comment by josevalim** [comment]
Surely! Can you please send a PR?
