### ISSUE TITLE
Safe ETS interactions

### ISSUE THREAD

**Issue by binaryseed** [beam-telemetry/telemetry#53]
We've seen an issue in Absinthe where a mix task is run that calls code which is instrumented with telemetry, but the handler lookup fails. The ETS table hadn't been created since telemetry wasn't started.

Given that the goal is to have telemetry embedded everywhere, should we rescue the `ArgumentError` that arises in cases like this?

https://github.com/beam-telemetry/telemetry/blob/9f009934f493719c2393adbe39eef3424411fd57/src/telemetry_handler_table.erl#L45-L47

https://github.com/absinthe-graphql/absinthe/issues/807

```
Compiling 1 file (.ex)
** (ArgumentError) argument error
    (stdlib) :ets.lookup(:telemetry_handler_table, [:absinthe, :execute, :operation, :start])
    /Users/Jaap/Documents/development/family-five/server/deps/telemetry/src/telemetry_handler_table.erl:47: :telemetry_handler_table.list_for_event/1
    /Users/Jaap/Documents/development/family-five/server/deps/telemetry/src/telemetry.erl:114: :telemetry.execute/3
    lib/absinthe/phase/telemetry.ex:18: Absinthe.Phase.Telemetry.run/2
    lib/absinthe/pipeline.ex:366: Absinthe.Pipeline.run_phase/3
    lib/absinthe.ex:110: Absinthe.run/3
    lib/mix/tasks/compile.schema_json.ex:12: Mix.Tasks.Compile.SchemaJson.run/1
```

**Comment by josevalim** [comment]
@binaryseed I am a bit worried that this will hide actual poor configuration and actual telemetry errors.

Shouldn't `Absinthe.run/3` or such API call `Application.ensure_all_started(:absinthe)` to make sure absinthe is properly started? Otherwise any dependency of absinthe won't run properly.

**Comment by tsloughter** [comment]
I support hiding. Unless it effects business logic I wouldn't want it to crash. If telemetry itself was not working in the actual application I would expect other facilities to notice (a health check that makes sure telemetry is functioning or an alert set on not getting metrics from an otherwise healthy node for a period f time) and restart the app if that is what I wanted to set up.

**Comment by binaryseed** [comment]
So I'd support both.

Absinthe itself _does_ start the app inside the mix tasks it defines. It looks like this blew up for a user who defined their own mix task & didn't start absinthe. I think they should start absinthe.

I also think that for encouraging widespread adoption & confidence, an instrumentation library should not crash, but rather log an error - that way it's not hidden from the user but it doesn't blow up on them & cause them to want to remove telemetry altogether (which is the reaction I've seen here and in other situations).

**Comment by josevalim** [comment]
Ah, for me it was being proposed to just discard. Yeah, I can definitely get behind logging.

**Comment by tsloughter** [comment]
It must be configurable, especially the log level. I prefer to keep `error` level as things that will page :)

But also should be able to turn off logs for it.

**Comment by binaryseed** [comment]
I started a PR, it logs a warning but doesn't configure the behavior yet... https://github.com/beam-telemetry/telemetry/pull/54
