### ISSUE TITLE
Errors in readme

### ISSUE THREAD

**Issue by aleklisi** [beam-telemetry/telemetry#55]
or `rebar.config`:
```
{deps, [{telemetry, "~> 0.4.1"}]}.
```
should be chaged to:
```
{deps, [{telemetry, "0.4.1"}]}.
```
for Erlang, at the end of readme.

Moreover, there is no 0.4.1 release so 0.4.0 should be used.

And also
```
telemetry:execute(
  [web, request, done],
  #{latency => Latency},
  #{request_path => Path, status_code => Status}
)
```
uses `request_path` while 
```
handle_event([web, request, done], #{latency := Latency}, #{path := Path,
                                                            status_code := Status}, _Config) ->
  ?LOG_INFO("[~s] ~p sent in ~p", [Path, Status, Latency]).
```
handler, matches to the key `path`. Which causes an error trying to copy-paste an example form Readme.

**Comment by josevalim** [comment]
FWIW, rebar should support the ~> 0.4.1 notation and v0.4.1 is listed on Hex: https://hex.pm/packages/telemetry

I will fix the rest, thanks!

**Comment by josevalim** [comment]
Done in 292c065.

**Comment by tsloughter** [comment]
Yes, rebar3 supports `~> 0.4.1`, no reason to change that.

**Comment by aleklisi** [comment]
@josevalim thank you very much for the quick reply 👍and the fix you provided
