### ISSUE TITLE
Nested payload for measurement?

### ISSUE THREAD

**Issue by anildigital** [beam-telemetry/telemetry#62]
I am thinking, can Telemetry be used to send event having a nested payload

```
:telemetry.execute(
  [:web, :request, :done],
  %{latency: latency},
  %{request_path: path, status_code: status}
)
```

But what if I need to emit an event with measurement as a payload which may be deeply nested map? Not sure if the type of measurement is documented. Or is it a limitation of available reporters only?

**Comment by josevalim** [comment]
The docs say it is a map but most reporterss and telemetry metrics assume that it is a map of atom keys with numeric values. And I think that's reasonable. It seems you can put whatever you want in there but you shouldn't expect all tools to be able to handle whatever you put in it. I would stick with `%{atom => number}`.
