### ISSUE TITLE
Release 0.4.2

### ISSUE THREAD

**Issue by josevalim** [beam-telemetry/telemetry#64]
We have added span/3 to telemetry, so it probably makes sense to build a new release. WDYT?

@arkgil, would you please do the honors when you are around? Thank you!

**Comment by arkgil** [comment]
Sure! I'd just tag it as 0.5.0.

**Comment by josevalim** [comment]
My concern is that a lot of projects have ~> 0.4.0 because they want to be strict given the fact SemVer does not guarantee any compatibility before 1.0. So my suggestion is to stick with the 0.4 branch while we can, to avoid conflicts, and probably release v1.0 next.

**Comment by arkgil** [comment]
@josevalim I see, makes sense!
