### ISSUE TITLE
What's the difference with gen_event?

### ISSUE THREAD

**Issue by manuel-rubio** [beam-telemetry/telemetry#68]
I was reading the code and, as far as I was checking it, it looks a copy of `gen_event`, it's been able to register handlers for every element propagated and if it's failing it's detached. Because maybe I was missing something, I'm curious, what's the difference with gen_event?

**Comment by josevalim** [comment]
In a nutshell: gen_event runs the events for all handlers in a server process - which may be a bottleneck. telemetry runs the handlers directly in the caller.
