### ISSUE TITLE
Shall we release 1.0?

### ISSUE THREAD

**Issue by josevalim** [beam-telemetry/telemetry#69]

**Comment by GregMefford** [comment]
Sure! 😁 :shipit:

**Comment by josevalim** [comment]
Fantastic. Btw, when updating dependencies that depend on telemetry, let's update them to: "~> 0.4 or ~> 1.0", so we don't force everyone to migrate to 1.0 immediately (or worse, have conflicting deps).

**Comment by whatyouhide** [comment]
👍 on this, it's great!

**Comment by tsloughter** [comment]
+1 with the caveat that we wait for https://github.com/erlang/rebar3/pull/2370 :)

**Comment by binaryseed** [comment]
Awesome!

I'd love to come to a decision on #48 but that shouldn't block a 1.0
