### ISSUE TITLE
Need for notification when handler is detached?

### ISSUE THREAD

**Issue by arkgil** [beam-telemetry/telemetry#8]
Right now the handler is detached whenever it fails. Additionally, handlers can be manually removed. However, there is now way to get notified when this happens, which means that one can not attempt to attach handler once again in hope that it won't fail this time (similarly we restart processes in hope that this time everything will work fine).

I believe that such mechanism should be added to the library. I imagine processes attaching handlers on spawn, listening on "detached events" and crashing when they're received, to ultimately be restarted and starting the cycle over again.

/cc @josevalim @chrismccord @studzien

**Comment by josevalim** [comment]
Yes, we will probably need something similar, although I am glad to wait until we have a bit more use cases. :+1:

**Comment by arkgil** [comment]
As mentioned in the discussion in #28, a good idea might be to emit an event when the handler is detached. This way one could log an error or reattach a failed handler.

**Comment by arkgil** [comment]
Closing this - no feedback or potential users of this functionality.
