### ISSUE TITLE
telemetry.beam failed: :badfile

### ISSUE THREAD

**Issue by eliduke** [beam-telemetry/telemetry#97]
Hey y'all!

Apologies if this is the wrong place to be posting this, but I am at my whits end. If there is a better place to be asking this question, please point in that direction if you have the time. I am new to elixir/Erlang and I'm not sure about a lot of things at this point, but here's where I'm at:

Been playing around with Elixir / Phoenix / LiveView, etc. Recently I got a LiveView testing course and the sample project is running Erlang 23, and I'm only (very loosely) familiar with 24. Anyhoo, I downloaded `asdf` and started to get things sorted. It was a BEAR getting 23 correctly installed with the right version of openssl and blah blah blah. Anyhoo, I *finally* got 23 to build correctly, but when I try running any tests at all, I see this a BUNCH of times:

```
22:52:06.135 [error] Loading of {project_dir}/_build/test/lib/telemetry/ebin/telemetry.beam failed: :badfile

22:52:06.135 [error] beam/beam_load.c(1886): Error loading module telemetry:
  This BEAM file was compiled for a later version of the run-time system than 23.
  To fix this, please recompile this module with an 23 compiler.
  (Use of opcode 172; this emulator supports only up to 170.)
```

And then eventually the running of the test fails with this error message:

```
could not compile dependency :phoenix_live_dashboard, "mix compile" failed. You can recompile this dependency with "mix deps.compile phoenix_live_dashboard", update it with "mix deps.update phoenix_live_dashboard" or clean it with "mix deps.clean phoenix_live_dashboard"
** (MatchError) no match of right hand side value: {:error, {:phoenix, {:bad_return, {{Phoenix, :start, [:normal, []]}, {:EXIT, {:undef, [{:telemetry, :attach, [{Phoenix.Logger, [:phoenix, :channel_handled_in]}, [:phoenix, :channel_handled_in], #Function<8.82939286/4 in Phoenix.Logger."-fun.phoenix_channel_handled_in/4-">, :ok], []}, {Phoenix.Logger, :"-install/0-fun-7-", 2, [file: 'lib/phoenix/logger.ex', line: 111]}, {:maps, :fold_1, 3, [file: 'maps.erl', line: 233]}, {Phoenix.Logger, :install, 0, [file: 'lib/phoenix/logger.ex', line: 110]}, {Phoenix, :start, 2, [file: 'lib/phoenix.ex', line: 46]}, {:application_master, :start_it_old, 4, [file: 'application_master.erl', line: 277]}]}}}}}}
    (phoenix 1.5.6) lib/mix/tasks/compile.phoenix.ex:11: Mix.Tasks.Compile.Phoenix.run/1
    (mix 1.11.2) lib/mix/task.ex:394: Mix.Task.run_task/3
    (mix 1.11.2) lib/mix/tasks/compile.all.ex:90: Mix.Tasks.Compile.All.run_compiler/2
    (mix 1.11.2) lib/mix/tasks/compile.all.ex:70: Mix.Tasks.Compile.All.compile/4
    (mix 1.11.2) lib/mix/tasks/compile.all.ex:57: Mix.Tasks.Compile.All.with_logger_app/2
    (mix 1.11.2) lib/mix/tasks/compile.all.ex:35: Mix.Tasks.Compile.All.run/1
    (mix 1.11.2) lib/mix/task.ex:394: Mix.Task.run_task/3
    (mix 1.11.2) lib/mix/tasks/compile.ex:119: Mix.Tasks.Compile.run/1
```

So...

1) Am I in the right place?
2) How exactly does one "recompile this module with an 23 compiler" ?
3) Do you have any other suggestions?

Thank you so much for your time!

**Comment by josevalim** [comment]
This is an Elixir bug that has recently be addressed. Delete `_build` and `deps` and you should be good to go, run `mix deps.get` again, and you should be good to go!

**Comment by eliduke** [comment]
@josevalim That did it! I deleting `_build` many times in my testing back and forth, but wasn't really aware of the `/deps` yet. Thanks so much for you help! Tests are running just fine now. :)
